name: active_fires_explorer
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - requests
  - pytz
  - pyproj
  - shapely
  - geopandas
  - gdal=3.8.3
  - pip
  - pip:
      - sepal_ui==2.21.0
      - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#subdirectory=python
      - shapely-geojson
      - rasterio<=1.4.3
