name: planet_active_fires_explorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyproj  # Always include to avoid PROJ conflicts
  - rasterio
  - numpy
  - pandas
  - geopandas
  - requests
  - pytz>=2020.1
  - cryptography>=2.1.4
  - colorlog
  - pip
  - pip:
    - shapely_geojson
    - git+https://github.com/openforis/sepal_ui@solara
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
