name: active_fires_explorer
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pyproj
  - gdal
  - numpy
  - pandas
  - geopandas
  - requests
  - shapely
  - pytz
  - pip
  - pip:
    - sepal_ui==2.21.0
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0
    - shapely-geojson